"""UNIFICATION core modules."""
from .addon_installer import (
    ADDON_FILE_NAME,
    ADDON_REMOTE_URL,
    BUNDLED_ADDON_PATH,
    AppAddonDir,
    BlenderAddonDir,
    fetch_remote_addon,
    find_blender_addon_dirs,
    find_freecad_addon_dirs,
    find_gimp_addon_dirs,
    install_addon,
    install_app_addon,
    open_addon_dir,
    open_app_addon_dir,
    read_bundled_version,
    uninstall_addon,
    uninstall_app_addon,
)
from .blender_client import (
    BlenderClient,
    BlenderResult,
    wrap_with_render,
    wrap_with_view3d_override,
)
from .i18n import LANGUAGE_LABELS, available_languages, get_language, set_language, t
from .lint import LintIssue, lint_python
from .llm_providers import (
    PROVIDER_LABELS,
    PROVIDERS,
    ClaudeProvider,
    GeminiProvider,
    LLMProvider,
    OllamaProvider,
    OpenAIProvider,
    create_provider,
)
from .ollama_client import (
    OllamaClient,
    OllamaModel,
    StreamStats,
    estimate_history_tokens,
    estimate_tokens,
    model_supports_vision,
    trim_history,
)
from .settings import HISTORY_PATH, LOG_PATH, Settings, load_history, save_history
from .system_prompt import (
    FREECAD_PROMPT,
    FREECAD_PROMPT_QUERY,
    GIMP_PROMPT,
    GIMP_PROMPT_QUERY,
    INKSCAPE_PROMPT,
    INKSCAPE_PROMPT_QUERY,
    PHOTOSHOP_PROMPT,
    PHOTOSHOP_PROMPT_QUERY,
    SYSTEM_PROMPT,
    SYSTEM_PROMPT_QUERY,
    detect_categories,
    is_query_intent,
    pick_system_prompt,
)
from .tcp_ping import CREATIVE_APPS, ping_tcp_addon
from .updater import UpdateInfo, check_for_update

__all__ = [
    "ADDON_FILE_NAME",
    "ADDON_REMOTE_URL",
    "BUNDLED_ADDON_PATH",
    "AppAddonDir",
    "BlenderAddonDir",
    "BlenderClient",
    "BlenderResult",
    "CREATIVE_APPS",
    "FREECAD_PROMPT",
    "FREECAD_PROMPT_QUERY",
    "GIMP_PROMPT",
    "HISTORY_PATH",
    "LANGUAGE_LABELS",
    "LOG_PATH",
    "LintIssue",
    "OllamaClient",
    "OllamaModel",
    "Settings",
    "StreamStats",
    "SYSTEM_PROMPT",
    "SYSTEM_PROMPT_QUERY",
    "UpdateInfo",
    "available_languages",
    "check_for_update",
    "estimate_history_tokens",
    "estimate_tokens",
    "fetch_remote_addon",
    "find_blender_addon_dirs",
    "find_freecad_addon_dirs",
    "find_gimp_addon_dirs",
    "get_language",
    "install_addon",
    "install_app_addon",
    "is_query_intent",
    "lint_python",
    "load_history",
    "model_supports_vision",
    "open_addon_dir",
    "open_app_addon_dir",
    "pick_system_prompt",
    "ping_tcp_addon",
    "read_bundled_version",
    "save_history",
    "set_language",
    "t",
    "trim_history",
    "uninstall_addon",
    "uninstall_app_addon",
    "wrap_with_render",
    "wrap_with_view3d_override",
]
